// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package ordersdb

import (
	"strconv"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/strmangle"
)

// M type is for providing columns and column values to UpdateAll.
type M map[string]interface{}

// ErrSyncFail occurs during insert when the record could not be retrieved in
// order to populate default value information. This usually happens when LastInsertId
// fails or there was a primary key configuration that was not resolvable.
var ErrSyncFail = errors.New("ordersdb: failed to synchronize data after insert")

type insertCache struct {
	query        string
	retQuery     string
	valueMapping []uint64
	retMapping   []uint64
}

type updateCache struct {
	query        string
	valueMapping []uint64
}

func makeCacheKey(cols boil.Columns, nzDefaults []string) string {
	buf := strmangle.GetBuffer()

	buf.WriteString(strconv.Itoa(cols.Kind))
	for _, w := range cols.Cols {
		buf.WriteString(w)
	}

	if len(nzDefaults) != 0 {
		buf.WriteByte('.')
	}
	for _, nz := range nzDefaults {
		buf.WriteString(nz)
	}

	str := buf.String()
	strmangle.PutBuffer(buf)
	return str
}

type OrderStatus string

// Enum values for OrderStatus
const (
	OrderStatusWORK_IN_PROGRESS OrderStatus = "WORK_IN_PROGRESS"
	OrderStatusCANCELED         OrderStatus = "CANCELED"
	OrderStatusCOMPLETED        OrderStatus = "COMPLETED"
	OrderStatusPREPARING        OrderStatus = "PREPARING"
)

func AllOrderStatus() []OrderStatus {
	return []OrderStatus{
		OrderStatusWORK_IN_PROGRESS,
		OrderStatusCANCELED,
		OrderStatusCOMPLETED,
		OrderStatusPREPARING,
	}
}

func (e OrderStatus) IsValid() error {
	switch e {
	case OrderStatusWORK_IN_PROGRESS, OrderStatusCANCELED, OrderStatusCOMPLETED, OrderStatusPREPARING:
		return nil
	default:
		return errors.New("enum is not valid")
	}
}

func (e OrderStatus) String() string {
	return string(e)
}

func (e OrderStatus) Ordinal() int {
	switch e {
	case OrderStatusWORK_IN_PROGRESS:
		return 0
	case OrderStatusCANCELED:
		return 1
	case OrderStatusCOMPLETED:
		return 2
	case OrderStatusPREPARING:
		return 3

	default:
		panic(errors.New("enum is not valid"))
	}
}
