// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package ordersdb

var TableNames = struct {
	CancelInstructions   string
	Products             string
	ReceivingDetails     string
	Receivings           string
	ShippingInstructions string
}{
	CancelInstructions:   "cancel_instructions",
	Products:             "products",
	ReceivingDetails:     "receiving_details",
	Receivings:           "receivings",
	ShippingInstructions: "shipping_instructions",
}
