// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package ordersdb

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// Receiving is an object representing the database table.
type Receiving struct { // 受注番号
	OrderNo string `boil:"order_no" json:"order_no" toml:"order_no" yaml:"order_no"`
	// 受注日
	OrderDate time.Time `boil:"order_date" json:"order_date" toml:"order_date" yaml:"order_date"`
	// 処理担当者名
	OperatorName string `boil:"operator_name" json:"operator_name" toml:"operator_name" yaml:"operator_name"`
	// 得意先名称
	CustomerName string `boil:"customer_name" json:"customer_name" toml:"customer_name" yaml:"customer_name"`
	// 受注金額
	TotalOrderPrice int `boil:"total_order_price" json:"total_order_price" toml:"total_order_price" yaml:"total_order_price"`
	// 受注残額
	RemainingOrderPrice int `boil:"remaining_order_price" json:"remaining_order_price" toml:"remaining_order_price" yaml:"remaining_order_price"`
	// 受注ステータス
	OrderStatus OrderStatus `boil:"order_status" json:"order_status" toml:"order_status" yaml:"order_status"`
	// 作成日時
	CreatedAt time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	// 更新日時
	UpdatedAt time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`
	// 作成者
	CreatedBy null.String `boil:"created_by" json:"created_by,omitempty" toml:"created_by" yaml:"created_by,omitempty"`
	// 更新者
	UpdatedBy null.String `boil:"updated_by" json:"updated_by,omitempty" toml:"updated_by" yaml:"updated_by,omitempty"`

	R *receivingR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L receivingL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var ReceivingColumns = struct {
	OrderNo             string
	OrderDate           string
	OperatorName        string
	CustomerName        string
	TotalOrderPrice     string
	RemainingOrderPrice string
	OrderStatus         string
	CreatedAt           string
	UpdatedAt           string
	CreatedBy           string
	UpdatedBy           string
}{
	OrderNo:             "order_no",
	OrderDate:           "order_date",
	OperatorName:        "operator_name",
	CustomerName:        "customer_name",
	TotalOrderPrice:     "total_order_price",
	RemainingOrderPrice: "remaining_order_price",
	OrderStatus:         "order_status",
	CreatedAt:           "created_at",
	UpdatedAt:           "updated_at",
	CreatedBy:           "created_by",
	UpdatedBy:           "updated_by",
}

var ReceivingTableColumns = struct {
	OrderNo             string
	OrderDate           string
	OperatorName        string
	CustomerName        string
	TotalOrderPrice     string
	RemainingOrderPrice string
	OrderStatus         string
	CreatedAt           string
	UpdatedAt           string
	CreatedBy           string
	UpdatedBy           string
}{
	OrderNo:             "receivings.order_no",
	OrderDate:           "receivings.order_date",
	OperatorName:        "receivings.operator_name",
	CustomerName:        "receivings.customer_name",
	TotalOrderPrice:     "receivings.total_order_price",
	RemainingOrderPrice: "receivings.remaining_order_price",
	OrderStatus:         "receivings.order_status",
	CreatedAt:           "receivings.created_at",
	UpdatedAt:           "receivings.updated_at",
	CreatedBy:           "receivings.created_by",
	UpdatedBy:           "receivings.updated_by",
}

// Generated where

var ReceivingWhere = struct {
	OrderNo             whereHelperstring
	OrderDate           whereHelpertime_Time
	OperatorName        whereHelperstring
	CustomerName        whereHelperstring
	TotalOrderPrice     whereHelperint
	RemainingOrderPrice whereHelperint
	OrderStatus         whereHelperOrderStatus
	CreatedAt           whereHelpertime_Time
	UpdatedAt           whereHelpertime_Time
	CreatedBy           whereHelpernull_String
	UpdatedBy           whereHelpernull_String
}{
	OrderNo:             whereHelperstring{field: "\"orders\".\"receivings\".\"order_no\""},
	OrderDate:           whereHelpertime_Time{field: "\"orders\".\"receivings\".\"order_date\""},
	OperatorName:        whereHelperstring{field: "\"orders\".\"receivings\".\"operator_name\""},
	CustomerName:        whereHelperstring{field: "\"orders\".\"receivings\".\"customer_name\""},
	TotalOrderPrice:     whereHelperint{field: "\"orders\".\"receivings\".\"total_order_price\""},
	RemainingOrderPrice: whereHelperint{field: "\"orders\".\"receivings\".\"remaining_order_price\""},
	OrderStatus:         whereHelperOrderStatus{field: "\"orders\".\"receivings\".\"order_status\""},
	CreatedAt:           whereHelpertime_Time{field: "\"orders\".\"receivings\".\"created_at\""},
	UpdatedAt:           whereHelpertime_Time{field: "\"orders\".\"receivings\".\"updated_at\""},
	CreatedBy:           whereHelpernull_String{field: "\"orders\".\"receivings\".\"created_by\""},
	UpdatedBy:           whereHelpernull_String{field: "\"orders\".\"receivings\".\"updated_by\""},
}

// ReceivingRels is where relationship names are stored.
var ReceivingRels = struct {
	OrderNoReceivingDetails string
}{
	OrderNoReceivingDetails: "OrderNoReceivingDetails",
}

// receivingR is where relationships are stored.
type receivingR struct {
	OrderNoReceivingDetails ReceivingDetailSlice `boil:"OrderNoReceivingDetails" json:"OrderNoReceivingDetails" toml:"OrderNoReceivingDetails" yaml:"OrderNoReceivingDetails"`
}

// NewStruct creates a new relationship struct
func (*receivingR) NewStruct() *receivingR {
	return &receivingR{}
}

func (r *receivingR) GetOrderNoReceivingDetails() ReceivingDetailSlice {
	if r == nil {
		return nil
	}
	return r.OrderNoReceivingDetails
}

// receivingL is where Load methods for each relationship are stored.
type receivingL struct{}

var (
	receivingAllColumns            = []string{"order_no", "order_date", "operator_name", "customer_name", "total_order_price", "remaining_order_price", "order_status", "created_at", "updated_at", "created_by", "updated_by"}
	receivingColumnsWithoutDefault = []string{"order_no", "operator_name", "customer_name"}
	receivingColumnsWithDefault    = []string{"order_date", "total_order_price", "remaining_order_price", "order_status", "created_at", "updated_at", "created_by", "updated_by"}
	receivingPrimaryKeyColumns     = []string{"order_no"}
	receivingGeneratedColumns      = []string{}
)

type (
	// ReceivingSlice is an alias for a slice of pointers to Receiving.
	// This should almost always be used instead of []Receiving.
	ReceivingSlice []*Receiving
	// ReceivingHook is the signature for custom Receiving hook methods
	ReceivingHook func(context.Context, boil.ContextExecutor, *Receiving) error

	receivingQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	receivingType                 = reflect.TypeOf(&Receiving{})
	receivingMapping              = queries.MakeStructMapping(receivingType)
	receivingPrimaryKeyMapping, _ = queries.BindMapping(receivingType, receivingMapping, receivingPrimaryKeyColumns)
	receivingInsertCacheMut       sync.RWMutex
	receivingInsertCache          = make(map[string]insertCache)
	receivingUpdateCacheMut       sync.RWMutex
	receivingUpdateCache          = make(map[string]updateCache)
	receivingUpsertCacheMut       sync.RWMutex
	receivingUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var receivingAfterSelectMu sync.Mutex
var receivingAfterSelectHooks []ReceivingHook

var receivingBeforeInsertMu sync.Mutex
var receivingBeforeInsertHooks []ReceivingHook
var receivingAfterInsertMu sync.Mutex
var receivingAfterInsertHooks []ReceivingHook

var receivingBeforeUpdateMu sync.Mutex
var receivingBeforeUpdateHooks []ReceivingHook
var receivingAfterUpdateMu sync.Mutex
var receivingAfterUpdateHooks []ReceivingHook

var receivingBeforeDeleteMu sync.Mutex
var receivingBeforeDeleteHooks []ReceivingHook
var receivingAfterDeleteMu sync.Mutex
var receivingAfterDeleteHooks []ReceivingHook

var receivingBeforeUpsertMu sync.Mutex
var receivingBeforeUpsertHooks []ReceivingHook
var receivingAfterUpsertMu sync.Mutex
var receivingAfterUpsertHooks []ReceivingHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Receiving) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range receivingAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Receiving) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range receivingBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Receiving) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range receivingAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Receiving) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range receivingBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Receiving) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range receivingAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Receiving) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range receivingBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Receiving) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range receivingAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Receiving) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range receivingBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Receiving) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range receivingAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddReceivingHook registers your hook function for all future operations.
func AddReceivingHook(hookPoint boil.HookPoint, receivingHook ReceivingHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		receivingAfterSelectMu.Lock()
		receivingAfterSelectHooks = append(receivingAfterSelectHooks, receivingHook)
		receivingAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		receivingBeforeInsertMu.Lock()
		receivingBeforeInsertHooks = append(receivingBeforeInsertHooks, receivingHook)
		receivingBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		receivingAfterInsertMu.Lock()
		receivingAfterInsertHooks = append(receivingAfterInsertHooks, receivingHook)
		receivingAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		receivingBeforeUpdateMu.Lock()
		receivingBeforeUpdateHooks = append(receivingBeforeUpdateHooks, receivingHook)
		receivingBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		receivingAfterUpdateMu.Lock()
		receivingAfterUpdateHooks = append(receivingAfterUpdateHooks, receivingHook)
		receivingAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		receivingBeforeDeleteMu.Lock()
		receivingBeforeDeleteHooks = append(receivingBeforeDeleteHooks, receivingHook)
		receivingBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		receivingAfterDeleteMu.Lock()
		receivingAfterDeleteHooks = append(receivingAfterDeleteHooks, receivingHook)
		receivingAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		receivingBeforeUpsertMu.Lock()
		receivingBeforeUpsertHooks = append(receivingBeforeUpsertHooks, receivingHook)
		receivingBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		receivingAfterUpsertMu.Lock()
		receivingAfterUpsertHooks = append(receivingAfterUpsertHooks, receivingHook)
		receivingAfterUpsertMu.Unlock()
	}
}

// OneG returns a single receiving record from the query using the global executor.
func (q receivingQuery) OneG(ctx context.Context) (*Receiving, error) {
	return q.One(ctx, boil.GetContextDB())
}

// One returns a single receiving record from the query.
func (q receivingQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Receiving, error) {
	o := &Receiving{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "ordersdb: failed to execute a one query for receivings")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// AllG returns all Receiving records from the query using the global executor.
func (q receivingQuery) AllG(ctx context.Context) (ReceivingSlice, error) {
	return q.All(ctx, boil.GetContextDB())
}

// All returns all Receiving records from the query.
func (q receivingQuery) All(ctx context.Context, exec boil.ContextExecutor) (ReceivingSlice, error) {
	var o []*Receiving

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "ordersdb: failed to assign all query results to Receiving slice")
	}

	if len(receivingAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountG returns the count of all Receiving records in the query using the global executor
func (q receivingQuery) CountG(ctx context.Context) (int64, error) {
	return q.Count(ctx, boil.GetContextDB())
}

// Count returns the count of all Receiving records in the query.
func (q receivingQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "ordersdb: failed to count receivings rows")
	}

	return count, nil
}

// ExistsG checks if the row exists in the table using the global executor.
func (q receivingQuery) ExistsG(ctx context.Context) (bool, error) {
	return q.Exists(ctx, boil.GetContextDB())
}

// Exists checks if the row exists in the table.
func (q receivingQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "ordersdb: failed to check if receivings exists")
	}

	return count > 0, nil
}

// OrderNoReceivingDetails retrieves all the receiving_detail's ReceivingDetails with an executor via order_no column.
func (o *Receiving) OrderNoReceivingDetails(mods ...qm.QueryMod) receivingDetailQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"orders\".\"receiving_details\".\"order_no\"=?", o.OrderNo),
	)

	return ReceivingDetails(queryMods...)
}

// LoadOrderNoReceivingDetails allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (receivingL) LoadOrderNoReceivingDetails(ctx context.Context, e boil.ContextExecutor, singular bool, maybeReceiving interface{}, mods queries.Applicator) error {
	var slice []*Receiving
	var object *Receiving

	if singular {
		var ok bool
		object, ok = maybeReceiving.(*Receiving)
		if !ok {
			object = new(Receiving)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeReceiving)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeReceiving))
			}
		}
	} else {
		s, ok := maybeReceiving.(*[]*Receiving)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeReceiving)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeReceiving))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &receivingR{}
		}
		args[object.OrderNo] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &receivingR{}
			}
			args[obj.OrderNo] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`orders.receiving_details`),
		qm.WhereIn(`orders.receiving_details.order_no in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load receiving_details")
	}

	var resultSlice []*ReceivingDetail
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice receiving_details")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on receiving_details")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for receiving_details")
	}

	if len(receivingDetailAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.OrderNoReceivingDetails = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &receivingDetailR{}
			}
			foreign.R.OrderNoReceiving = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.OrderNo == foreign.OrderNo {
				local.R.OrderNoReceivingDetails = append(local.R.OrderNoReceivingDetails, foreign)
				if foreign.R == nil {
					foreign.R = &receivingDetailR{}
				}
				foreign.R.OrderNoReceiving = local
				break
			}
		}
	}

	return nil
}

// AddOrderNoReceivingDetailsG adds the given related objects to the existing relationships
// of the receiving, optionally inserting them as new records.
// Appends related to o.R.OrderNoReceivingDetails.
// Sets related.R.OrderNoReceiving appropriately.
// Uses the global database handle.
func (o *Receiving) AddOrderNoReceivingDetailsG(ctx context.Context, insert bool, related ...*ReceivingDetail) error {
	return o.AddOrderNoReceivingDetails(ctx, boil.GetContextDB(), insert, related...)
}

// AddOrderNoReceivingDetails adds the given related objects to the existing relationships
// of the receiving, optionally inserting them as new records.
// Appends related to o.R.OrderNoReceivingDetails.
// Sets related.R.OrderNoReceiving appropriately.
func (o *Receiving) AddOrderNoReceivingDetails(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*ReceivingDetail) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.OrderNo = o.OrderNo
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"orders\".\"receiving_details\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"order_no"}),
				strmangle.WhereClause("\"", "\"", 2, receivingDetailPrimaryKeyColumns),
			)
			values := []interface{}{o.OrderNo, rel.OrderNo, rel.ProductID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.OrderNo = o.OrderNo
		}
	}

	if o.R == nil {
		o.R = &receivingR{
			OrderNoReceivingDetails: related,
		}
	} else {
		o.R.OrderNoReceivingDetails = append(o.R.OrderNoReceivingDetails, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &receivingDetailR{
				OrderNoReceiving: o,
			}
		} else {
			rel.R.OrderNoReceiving = o
		}
	}
	return nil
}

// Receivings retrieves all the records using an executor.
func Receivings(mods ...qm.QueryMod) receivingQuery {
	mods = append(mods, qm.From("\"orders\".\"receivings\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"orders\".\"receivings\".*"})
	}

	return receivingQuery{q}
}

// FindReceivingG retrieves a single record by ID.
func FindReceivingG(ctx context.Context, orderNo string, selectCols ...string) (*Receiving, error) {
	return FindReceiving(ctx, boil.GetContextDB(), orderNo, selectCols...)
}

// FindReceiving retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindReceiving(ctx context.Context, exec boil.ContextExecutor, orderNo string, selectCols ...string) (*Receiving, error) {
	receivingObj := &Receiving{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"orders\".\"receivings\" where \"order_no\"=$1", sel,
	)

	q := queries.Raw(query, orderNo)

	err := q.Bind(ctx, exec, receivingObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "ordersdb: unable to select from receivings")
	}

	if err = receivingObj.doAfterSelectHooks(ctx, exec); err != nil {
		return receivingObj, err
	}

	return receivingObj, nil
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *Receiving) InsertG(ctx context.Context, columns boil.Columns) error {
	return o.Insert(ctx, boil.GetContextDB(), columns)
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Receiving) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("ordersdb: no receivings provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(receivingColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	receivingInsertCacheMut.RLock()
	cache, cached := receivingInsertCache[key]
	receivingInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			receivingAllColumns,
			receivingColumnsWithDefault,
			receivingColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(receivingType, receivingMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(receivingType, receivingMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"orders\".\"receivings\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"orders\".\"receivings\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "ordersdb: unable to insert into receivings")
	}

	if !cached {
		receivingInsertCacheMut.Lock()
		receivingInsertCache[key] = cache
		receivingInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// UpdateG a single Receiving record using the global executor.
// See Update for more documentation.
func (o *Receiving) UpdateG(ctx context.Context, columns boil.Columns) (int64, error) {
	return o.Update(ctx, boil.GetContextDB(), columns)
}

// Update uses an executor to update the Receiving.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Receiving) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	receivingUpdateCacheMut.RLock()
	cache, cached := receivingUpdateCache[key]
	receivingUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			receivingAllColumns,
			receivingPrimaryKeyColumns,
		)
		if len(wl) == 0 {
			return 0, errors.New("ordersdb: unable to update receivings, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"orders\".\"receivings\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, receivingPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(receivingType, receivingMapping, append(wl, receivingPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "ordersdb: unable to update receivings row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "ordersdb: failed to get rows affected by update for receivings")
	}

	if !cached {
		receivingUpdateCacheMut.Lock()
		receivingUpdateCache[key] = cache
		receivingUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAllG updates all rows with the specified column values.
func (q receivingQuery) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return q.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values.
func (q receivingQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "ordersdb: unable to update all for receivings")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "ordersdb: unable to retrieve rows affected for receivings")
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (o ReceivingSlice) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return o.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o ReceivingSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("ordersdb: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), receivingPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"orders\".\"receivings\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, receivingPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "ordersdb: unable to update all in receiving slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "ordersdb: unable to retrieve rows affected all in update all receiving")
	}
	return rowsAff, nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *Receiving) UpsertG(ctx context.Context, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	return o.Upsert(ctx, boil.GetContextDB(), updateOnConflict, conflictColumns, updateColumns, insertColumns, opts...)
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Receiving) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("ordersdb: no receivings provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(receivingColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	receivingUpsertCacheMut.RLock()
	cache, cached := receivingUpsertCache[key]
	receivingUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			receivingAllColumns,
			receivingColumnsWithDefault,
			receivingColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			receivingAllColumns,
			receivingPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("ordersdb: unable to upsert receivings, could not build update column list")
		}

		ret := strmangle.SetComplement(receivingAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(receivingPrimaryKeyColumns) == 0 {
				return errors.New("ordersdb: unable to upsert receivings, could not build conflict column list")
			}

			conflict = make([]string, len(receivingPrimaryKeyColumns))
			copy(conflict, receivingPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"orders\".\"receivings\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(receivingType, receivingMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(receivingType, receivingMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "ordersdb: unable to upsert receivings")
	}

	if !cached {
		receivingUpsertCacheMut.Lock()
		receivingUpsertCache[key] = cache
		receivingUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// DeleteG deletes a single Receiving record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *Receiving) DeleteG(ctx context.Context) (int64, error) {
	return o.Delete(ctx, boil.GetContextDB())
}

// Delete deletes a single Receiving record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Receiving) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("ordersdb: no Receiving provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), receivingPrimaryKeyMapping)
	sql := "DELETE FROM \"orders\".\"receivings\" WHERE \"order_no\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "ordersdb: unable to delete from receivings")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "ordersdb: failed to get rows affected by delete for receivings")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

func (q receivingQuery) DeleteAllG(ctx context.Context) (int64, error) {
	return q.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all matching rows.
func (q receivingQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("ordersdb: no receivingQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "ordersdb: unable to delete all from receivings")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "ordersdb: failed to get rows affected by deleteall for receivings")
	}

	return rowsAff, nil
}

// DeleteAllG deletes all rows in the slice.
func (o ReceivingSlice) DeleteAllG(ctx context.Context) (int64, error) {
	return o.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o ReceivingSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(receivingBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), receivingPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"orders\".\"receivings\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, receivingPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "ordersdb: unable to delete all from receiving slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "ordersdb: failed to get rows affected by deleteall for receivings")
	}

	if len(receivingAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// ReloadG refetches the object from the database using the primary keys.
func (o *Receiving) ReloadG(ctx context.Context) error {
	if o == nil {
		return errors.New("ordersdb: no Receiving provided for reload")
	}

	return o.Reload(ctx, boil.GetContextDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Receiving) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindReceiving(ctx, exec, o.OrderNo)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ReceivingSlice) ReloadAllG(ctx context.Context) error {
	if o == nil {
		return errors.New("ordersdb: empty ReceivingSlice provided for reload all")
	}

	return o.ReloadAll(ctx, boil.GetContextDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ReceivingSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := ReceivingSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), receivingPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"orders\".\"receivings\".* FROM \"orders\".\"receivings\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, receivingPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "ordersdb: unable to reload all in ReceivingSlice")
	}

	*o = slice

	return nil
}

// ReceivingExistsG checks if the Receiving row exists.
func ReceivingExistsG(ctx context.Context, orderNo string) (bool, error) {
	return ReceivingExists(ctx, boil.GetContextDB(), orderNo)
}

// ReceivingExists checks if the Receiving row exists.
func ReceivingExists(ctx context.Context, exec boil.ContextExecutor, orderNo string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"orders\".\"receivings\" where \"order_no\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, orderNo)
	}
	row := exec.QueryRowContext(ctx, sql, orderNo)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "ordersdb: unable to check if receivings exists")
	}

	return exists, nil
}

// Exists checks if the Receiving row exists.
func (o *Receiving) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return ReceivingExists(ctx, exec, o.OrderNo)
}
