services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: ${API_NAME}-swagger-ui
    ports:
      - "${SWAGGER_UI_PORT}:8080"
    volumes:
      - ./openapi/${API_NAME}/openapi.yaml:/openapi.yaml
    environment:
      SWAGGER_JSON: /openapi.yaml

  mock-api:
    image: stoplight/prism:3
    container_name: ${API_NAME}-mock-api
    ports:
      - "${MOCK_SERVER_PORT}:4010"
    volumes:
      - ./openapi/${API_NAME}/openapi.yaml:/openapi.yaml
    command: mock -h 0.0.0.0 /openapi.yaml

networks:
  default:
    name: app_network
    external: true
