// Package apispec provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package apispec

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for OrderStatus.
const (
	CANCELED       OrderStatus = "CANCELED"
	COMPLETED      OrderStatus = "COMPLETED"
	PREPARING      OrderStatus = "PREPARING"
	WORKINPROGRESS OrderStatus = "WORK_IN_PROGRESS"
)

// CancelInstructionBody キャンセル指示登録
type CancelInstructionBody struct {
	// OperatorName 担当者名称
	OperatorName OperatorName `json:"operatorName"`

	// OrderNo 受注番号
	OrderNo OrderNo `json:"orderNo"`

	// ProductId 商品ID
	ProductId ProductId `json:"productId"`

	// Quantity 数量
	Quantity Quantity `json:"quantity"`

	// Reason 備考
	Reason *Note `json:"reason,omitempty"`
}

// Error エラーレスポンス
type Error struct {
	// Detail 備考
	Detail *Note `json:"detail,omitempty"`

	// Title 備考
	Title *Note `json:"title,omitempty"`

	// Types パス
	Types UrlPath `json:"types"`
}

// Receiving 受注
type Receiving struct {
	// CustomerName 受注先企業名
	CustomerName CustomerName `json:"customerName"`

	// OperatorName 担当者名称
	OperatorName OperatorName `json:"operatorName"`

	// OrderDate 日付
	OrderDate SysDate `json:"orderDate"`

	// OrderNo 受注番号
	OrderNo OrderNo `json:"orderNo"`

	// OrderStatus 受注状況
	OrderStatus OrderStatus `json:"orderStatus"`

	// RemainingOrderPrice 金額
	RemainingOrderPrice Price `json:"remainingOrderPrice"`

	// TotalOrderPrice 金額
	TotalOrderPrice Price `json:"totalOrderPrice"`
}

// ReceivingArray 受注の集合
type ReceivingArray = []Receiving

// ReceivingDetail 受注明細
type ReceivingDetail struct {
	// CancelQuantity 数量
	CancelQuantity Quantity `json:"cancelQuantity"`

	// CostPrice 金額
	CostPrice Price `json:"costPrice"`

	// OrderQuantity 数量
	OrderQuantity Quantity `json:"orderQuantity"`

	// OrderStatus 受注状況
	OrderStatus OrderStatus `json:"orderStatus"`

	// ProductId 商品ID
	ProductId ProductId `json:"productId"`

	// ProfitRate 利益額/売価
	ProfitRate ProfitRate `json:"profitRate"`

	// RemainingQuantity 数量
	RemainingQuantity Quantity `json:"remainingQuantity"`

	// SellingPrice 金額
	SellingPrice Price `json:"sellingPrice"`

	// ShippingQuantity 数量
	ShippingQuantity Quantity `json:"shippingQuantity"`
}

// ReceivingDetailArray 受注明細
type ReceivingDetailArray = []ReceivingDetail

// ReceivingOperatorBody 受注変更
type ReceivingOperatorBody struct {
	// OperatorName 担当者名称
	OperatorName OperatorName `json:"operatorName"`
}

// ReceivingPostBody 受注登録
type ReceivingPostBody struct {
	// CustomerName 受注先企業名
	CustomerName CustomerName `json:"customerName"`

	// Details 受注明細
	Details ReceivingPostDetailArray `json:"details"`

	// OperatorName 担当者名称
	OperatorName OperatorName `json:"operatorName"`
}

// ReceivingPostDetail 受注明細
type ReceivingPostDetail struct {
	// OrderQuantity 数量
	OrderQuantity Quantity `json:"orderQuantity"`

	// ProductId 商品ID
	ProductId ProductId `json:"productId"`

	// SellingPrice 金額
	SellingPrice Price `json:"sellingPrice"`
}

// ReceivingPostDetailArray 受注明細
type ReceivingPostDetailArray = []ReceivingPostDetail

// ReceivingWithDetail 受注
type ReceivingWithDetail struct {
	// CustomerName 受注先企業名
	CustomerName CustomerName `json:"customerName"`

	// Details 受注明細
	Details ReceivingDetailArray `json:"details"`

	// OperatorName 担当者名称
	OperatorName OperatorName `json:"operatorName"`

	// OrderDate 日付
	OrderDate SysDate `json:"orderDate"`

	// OrderNo 受注番号
	OrderNo OrderNo `json:"orderNo"`

	// OrderStatus 受注状況
	OrderStatus OrderStatus `json:"orderStatus"`

	// RemainingOrderPrice 金額
	RemainingOrderPrice Price `json:"remainingOrderPrice"`

	// TotalOrderPrice 金額
	TotalOrderPrice Price `json:"totalOrderPrice"`
}

// ShippingInstructionBody 出荷指示登録
type ShippingInstructionBody struct {
	// OperatorName 担当者名称
	OperatorName OperatorName `json:"operatorName"`

	// OrderNo 受注番号
	OrderNo OrderNo `json:"orderNo"`

	// ProductId 商品ID
	ProductId ProductId `json:"productId"`

	// Quantity 数量
	Quantity Quantity `json:"quantity"`
}

// CustomerName 受注先企業名
type CustomerName = string

// Limit 検索結果の取得数上限値
type Limit = int

// Note 備考
type Note = string

// Offset 検索実行時のオフセット値
type Offset = int

// OperatorName 担当者名称
type OperatorName = string

// OrderNo 受注番号
type OrderNo = string

// OrderStatus 受注状況
type OrderStatus string

// Price 金額
type Price = int

// ProductId 商品ID
type ProductId = string

// ProfitRate 利益額/売価
type ProfitRate = float32

// Quantity 数量
type Quantity = int

// SysDate 日付
type SysDate = openapi_types.Date

// TraceId ゲートウェイが発行する識別キー
type TraceId = string

// UrlPath パス
type UrlPath = string

// ErrorResponse エラーレスポンス
type ErrorResponse = Error

// OrdersCancelInstructionsPostParams defines parameters for OrdersCancelInstructionsPost.
type OrdersCancelInstructionsPostParams struct {
	XTaraceId TraceId `json:"x-tarace-id"`
}

// OrdersReceivingsGetParams defines parameters for OrdersReceivingsGet.
type OrdersReceivingsGetParams struct {
	// Limit 検索結果数上限値(デフォルト値は20)
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset 検索オフセット値(デフォルト値は0)
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`

	// CustomerName 【検索条件】得意先名称（完全一致）
	CustomerName *CustomerName `form:"customer_name,omitempty" json:"customer_name,omitempty"`

	// OrderStatus 【検索条件】受注ステータス
	OrderStatus *OrderStatus `form:"order_status,omitempty" json:"order_status,omitempty"`
	XTaraceId   TraceId      `json:"x-tarace-id"`
}

// OrdersReceivingsPostParams defines parameters for OrdersReceivingsPost.
type OrdersReceivingsPostParams struct {
	XTaraceId TraceId `json:"x-tarace-id"`
}

// OrdersReceivingsNoGetParams defines parameters for OrdersReceivingsNoGet.
type OrdersReceivingsNoGetParams struct {
	XTaraceId TraceId `json:"x-tarace-id"`
}

// OrdersReceivingsNoOperatorPutParams defines parameters for OrdersReceivingsNoOperatorPut.
type OrdersReceivingsNoOperatorPutParams struct {
	XTaraceId TraceId `json:"x-tarace-id"`
}

// OrdersShippingInstructionsPostParams defines parameters for OrdersShippingInstructionsPost.
type OrdersShippingInstructionsPostParams struct {
	XTaraceId TraceId `json:"x-tarace-id"`
}

// OrdersCancelInstructionsPostJSONRequestBody defines body for OrdersCancelInstructionsPost for application/json ContentType.
type OrdersCancelInstructionsPostJSONRequestBody = CancelInstructionBody

// OrdersReceivingsPostJSONRequestBody defines body for OrdersReceivingsPost for application/json ContentType.
type OrdersReceivingsPostJSONRequestBody = ReceivingPostBody

// OrdersReceivingsNoOperatorPutJSONRequestBody defines body for OrdersReceivingsNoOperatorPut for application/json ContentType.
type OrdersReceivingsNoOperatorPutJSONRequestBody = ReceivingOperatorBody

// OrdersShippingInstructionsPostJSONRequestBody defines body for OrdersShippingInstructionsPost for application/json ContentType.
type OrdersShippingInstructionsPostJSONRequestBody = ShippingInstructionBody
